services:
  db:
    image: postgres:11.15-bullseye
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./pginit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    networks:
      - test-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 2048M
        reservations:
          cpus: '0.1'
          memory: 1536M
  zookeeper:
    image: kymeric/cp-zookeeper:latest
    networks:
      - test-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.01'
          memory: 256M
  kafka:
    image: kymeric/cp-kafka:latest
    networks:
      - test-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.01'
          memory: 256M
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - test-network
    depends_on:
      - kafka
    ports:
      - 18080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.01'
          memory: 128M

networks:
  test-network:
    driver: bridge
volumes:
  postgres-data:
    external: false
